# Generated by Django 3.2 on 2021-04-28 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=30)),
                ('street', models.CharField(max_length=30)),
                ('city', models.CharField(max_length=30)),
                ('number', models.PositiveIntegerField()),
                ('phone_number', models.CharField(max_length=30)),
                ('title', models.CharField(choices=[('PhD', 'PhD Student'), ('PD', 'Postdoctoral'), ('HbD', 'Habilitated doctor'), ('Prof', 'Professor')], max_length=4)),
            ],
        ),
    ]
