# Generated by Django 3.2 on 2021-04-28 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='price_for_visit',
            field=models.PositiveIntegerField(default=100),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='number',
            field=models.PositiveIntegerField(default=100),
        ),
    ]
